---
all:
  children:
    production:
      hosts:
        production:
          ansible_host: dockolith.pequod.dev
          ansible_user: deploy
          ansible_ssh_private_key_file: ~/.ssh/scv
          ansible_python_interpreter: /usr/bin/python3

          # App settings
          app_name: wordle-group
          db_name: wordlegroup_production
          db_user: wordlegroup
          web_root: /var/data

          # Additional users for SSH access
          additional_users:
            - name: erik
              groups: [sudo]
              ssh_public_key_path: "~/.ssh/erik.pub"

          # fail2ban whitelist
          fail2ban_ignoreip:
            - 127.0.0.1/8
            - ::1
            - erikwestlund.ddns.net
